### ISSUE TITLE
repAssess: error that vector element is required

### ISSUE THREAD

**Issue by steffenoppel** [BirdLifeInternational/track2kba#21]
I got the following error when trying to use repAssess with vulture tracking data:

 Error in stack.default(KDE.Surface) : 
  at least one vector element is required 
5.
stop("at least one vector element is required") 
4.
stack.default(KDE.Surface) 
3.
stack(KDE.Surface) 
2.
stack(KDE.Surface) at C:\STEFFEN\track2iba\R\repAssess.r#100
1.
repAssess(DataGroup = alltrackdata, KDE = KDE.Surface, Scale = 5, 
    Iteration = 100, BootTable = F)

**Comment by steffenoppel** [comment]
Two days later with similar data on the same system I get a totally different error message: > repr <- repAssess(DataGroup=alltrackdata,KDE=KDE.Surface, Scale=5, Iteration=100, BootTable = F)
 Hide Traceback
 
 Rerun with Debug
 Error in { : 
  task 1 failed - "unable to find an inherited method for function ‘calc’ for signature ‘"NULL", "standardGeneric"’" 
4.
stop(simpleError(msg, call = expr)) 
3.
e$fun(obj, substitute(ex), parent.frame(), e$data) 
2.
foreach::foreach(LoopN = LoopNr, .combine = rbind, .packages = c("sp", 
    "dplyr", "raster")) %do% {
    N <- DoubleLoop$SampleSize[LoopN]
    i <- DoubleLoop$Iteration[LoopN] ... at C:\STEFFEN\track2iba\R\repAssess.r#110
1.
repAssess(DataGroup = alltrackdata, KDE = KDE.Surface, Scale = 5, 
    Iteration = 100, BootTable = F)

**Comment by MartinBeal** [comment]
Marie Claire, in my lab group, has been trying the package out recently and got the second error as well for Scopoli's data. I thought I solved this issue by using 'raster::calc()' but apparently not. 

I think it has to do with the selection/filtering step just before the calc() call in the foreach() loop.

**Comment by MartinBeal** [comment]
Still unclear about where this issue stems from. Tried two different data sets on my computer and repAssess works just fine. 

@steffenoppel could you try running the package dataset ( call: data(boobies) ) and see if you get the same error? That way we can see if it is a local environment issue, a data set configuration issue, or something else.

**Comment by MartinBeal** [comment]
I figured out the first issue, which had to do with converting an adehabitat estUDm object to a rasterStack. Not sure if my fix extends to the second one as well.
