### ISSUE TITLE
package renamed - change README.Rmd

### ISSUE THREAD

**Issue by lizziepear** [BirdLifeInternational/track2kba#25]
Edit README.Rmd and re-make README.md to update the installation instructions to 'track2kba' instead of 'track2iba'

**Comment by MartinBeal** [comment]
Apparently to use GitKraken (the GUI) with a BirdLife repo, BirdLife has to
grant access to it. It requested this, and it said an email was sent. Do
you know who to? Would that be you?

Martin

**Comment by lizziepear** [comment]
Sorry Martin! I can approve that, probably ought to check with IT as
they're the ultimate arbiters of the BL GitHub (but they agreed to make me
an admin). I'll try and sort it asap
