### ISSUE TITLE
repAssess: Parallel processing doesn't seem to work

### ISSUE THREAD

**Issue by MartinBeal** [BirdLifeInternational/track2kba#27]
I added back in the code for setting up parallel processing (because new weighted.means() calculation is slow), but when I compare the speeds across a range of Ncores, nothing changes. 

@steffenoppel do you think you could take a look at this? Since there's no error given I don't know where to begin and I think it was you who added this code in originally, so wondering if perhaps you have an idea?

**Comment by steffenoppel** [comment]
Without running it on any test data, it seems that you set Ncores to 2 (L. 115)? That will not yield much improvement, so we may need to take this out and ensure that max N of cores is used? Or did you do that manually when you say you tried 'range of Ncores'?
Your ressource monitor should clearly indicate how many cores are being engaged when you do that. I will try this now.

**Comment by MartinBeal** [comment]
Oh ya that might be the problem. Ya I just set that to 2 while testing
things in 'debug'.

**Comment by steffenoppel** [comment]
fixed this issue by commenting out the Ncores line, so repAssess now uses the number of cores specified in the function call
