### ISSUE TITLE
Error in sp::CRS(SRS_string = "EPSG:4326") :    no arguments in initialization list

### ISSUE THREAD

**Issue by clairemason** [BirdLifeInternational/track2kba#34]
Hello there, really excited to use the tripSplit function for my data, thanks for creating !! 

However, I'm stuck on this error when I run tripSplit-
**_Error in sp::CRS(SRS_string = "EPSG:4326") :    no arguments in initialization list_**

Calling traceback() shows this-
```{r}
> traceback()
9: stop(res[[2]])
8: sp::CRS(SRS_string = "EPSG:4326")
7: initialize(value, ...)
6: initialize(value, ...)
5: new("SpatialPoints", coords = coords, bbox = bbox, proj4string = proj4string)
4: SpatialPoints(data.frame(dataGroup$Longitude, dataGroup$Latitude), 
       proj4string = sp::CRS(SRS_string = "EPSG:4326"))
3: is(coords, "SpatialPoints")
2: SpatialPointsDataFrame(SpatialPoints(data.frame(dataGroup$Longitude, 
       dataGroup$Latitude), proj4string = sp::CRS(SRS_string = "EPSG:4326")), 
       data = dataGroup, match.ID = FALSE)
1: track2KBA::tripSplit(data_xy_id1, ai, innerBuff = 2, returnBuff = 20, 
       duration = 5, nests = FALSE, rmNonTrip = FALSE)

```
I've attached a minimum reproducible data and code example. 
I'm wondering whether I need to change the default CRS?
Any advice is very much appreciated! 

[data_xy_id1.zip](https://github.com/BirdLifeInternational/track2kba/files/4998114/data_xy_id1.zip)

``` {r}

install.packages("devtools", dependencies = TRUE)
devtools::install_github("BirdLifeInternational/track2kba", dependencies=TRUE) 
library(track2KBA)

xy_df_id1<- readRDS("xy_df_id1.R")

#coordinates of the colony
ai <- data.frame(Longitude = 144.6554, Latitude  = -40.3782)

trips <- track2KBA::tripSplit(xy_df_id1, 
                   ai, 
                   innerBuff=2,     # kilometers
                   returnBuff=20,
                   duration=5,      # hours
                   nests=FALSE, 
                   rmNonTrip=FALSE)

##Error in sp::CRS(SRS_string = "EPSG:4326") : 
##  no arguments in initialization list
traceback()

```

**Comment by MartinBeal** [comment]
I couldn't reproduce the error, and I believe this has to do with the ongoing changes to the `rgdal` `sf` and `sp` packages and the underlying `PROJ` library. (see more info [here](https://www.r-spatial.org//r/2020/03/17/wkt.html) and [here](http://rgdal.r-forge.r-project.org/articles/PROJ6_GDAL3.html). 

Try updating your rgdal, sf, and sp packages to the latest versions. I haven't figured out which minimum versions are necessary for these syntax changes, so if this works for you, please let me know what package versions you had before and after. Thanks!

**Comment by clairemason** [comment]
Hello @MartinBeal thanks so much for your quick reply and assistance. 

I have updated my package versions: 
'sp' from 1.4.1 to 1.4.5
'sf' from 0.9.2 to 0.9.5
'rgdal' from 1.4.8 to 1.5.12 

And this seemed to work! Thanks so much!!!
