### ISSUE TITLE
mapTrips: further refinements

### ISSUE THREAD

**Issue by MartinBeal** [BirdLifeInternational/track2kba#37]
So I admit I couldn't really figure out how to test the code changes you made @VirginiaMorerawhen when it was just a pull request. Now I've tested it and found a few things that would be nice to change if possible: 

1. The colors for tripIDs count across individuals, could this be done within individual? So that trip 1 for individuals A and B are the same color? When I ran this on the boobies test dataset there was a color scale of over a hundred colors!
2. The color scale for tripIDs counts by characters, so when they go above 10 they get ordered like '1, 10, 11...etc' (see map below). Would it be straightforward to convert these to numeric? (e.g. split the tripID from the individual ID, then convert that to numeric?).

![mapTrips_tripIDs](https://user-images.githubusercontent.com/45400296/97325291-b65bc680-186a-11eb-9555-21910f41c539.png)

FYI I've made a few adjustments to the function, so make sure to pull the latest version.

**Comment by steffenoppel** [comment]
This is exactly what I mentioned in Issue 35 [here](https://github.com/BirdLifeInternational/track2kba/issues/35#issuecomment-703727456).

I thought Virginia solved that? Maybe some code wasn't properly adopted?

**Comment by VirginiaMorera** [comment]
Yeah, I thought I had! Will take a proper look as soon as possible,
although it might not be immediate!

**Comment by MartinBeal** [comment]
No worries, the function works as is so it's not an acute issue. 

If you end up needing to use a function which is not already listed in the NAMESPACE at the top of the script, just below the help manual info, please add the new function there. e.g. #' @importFrom ggplot2 aes_string 

If possible, avoid using functions from a package which is not already listed in the NAMESPACE file of the package, so that we don't expand the already extensive dependency list of this package. 

Thanks!

**Comment by VirginiaMorera** [comment]
Ok, with the version I have saved offline, with the changes I originally made, the same 4 ind look like this (with trip number restarting at each plot)
![imagen](https://user-images.githubusercontent.com/11058769/100348029-95f86680-2fe6-11eb-9b68-0775b650300d.png)

So I imagine at some point either when I made the changes here or when you changed the name of the argument and added the default to colour by completeness, something went amiss. I'm trying to figure out what right now, which I guess is the point of version control & GitHub, but I still don't quite get how to do that easily...

**Comment by MartinBeal** [comment]
Looks great! I don't really find version control so useful for debugging.
Mostly just for being able to backtrack if something goes horribly wrong.
The one thing I do do is check side-by-side comparisons of changes if I
suspect a specific commit introduced the issue.
