### ISSUE TITLE
main issues to solve

### ISSUE THREAD

**Issue by steffenoppel** [BirdLifeInternational/track2kba#4]
Main changes to existing functions: 
A. tripSplit: Martin
	1. build in option to loop over grouping variable (e.g. colony/year)
B. tripSummary: Steffen 
	2. What changes?
C. scaleARS: Jono + Martin
	1. use device type to define seq (PTT: 5-250 km, GPS 0-250 km)
        2. use temporal data resolution to define intervals
        3. include error message if no ARS scale is sensible because no ARS recommendations for the interval of scales for FPT analysis. (i.e based on Oppel et al. 2018 figures.)
D. batchUD: Anyone
	1. Check how simple features objects interact with adehabitat functions
E. varianceTest:
	1. Perhaps replace with Virginia’s IndEffectTest()
F. Bootstrap: Martin + Lizzie 
	1. (MB) Add visualization option (relationship btwn sample size and area used)
	2. (MB) Check if it could speed things up to make the number of combinations run dependent on the number of possible combinations at each sample size (Bootstrapping is WITH 	replacement so maybe moot point).
	3. Test and assure cluster functionality (LP)
G. polyCount: Steffen + Martin
H. thresholdRaster: Steffen + Martin
	- Combine these two functions into one (e.g. FindIba function) by setting the threshold first and counting overlapping UD polygons rather than gridded polygons. 
		o Advantage of polygon output rather than grid cell output defined by subjective grid resolution. 

General things to work on:
	- Translating to Tidyverse syntax
	- Simple Features (SEE Issues page on this)
	- Testing against all data types we have!!

**Comment by Ailfer** [comment]
Hi, I would like to ask if this "track2KBA" R package can be applied to the identification of key areas of macrofungal biodiversity?

**Comment by steffenoppel** [comment]
Hi Ailfer, unfortunately not. Our package is based on telemetry data of individual animals - it is not based on surveys where you count how many species occur in a given area. This package is therefore NOT suitable to identify key areas of biodiversity where your input data are species lists or predictions (as I expect would be the case for fungi).

**Comment by Ailfer** [comment]
> 嗨，艾尔弗，不幸的是不是。我们的软件包基于单个动物的遥测数据 - 它不是基于您计算给定区域中出现多少物种的调查。因此，此软件包不适合确定生物多样性的关键区域，其中您的输入数据是物种列表或预测（正如我所期望的那样真菌）。

Ok, thank you for your reply!

**Comment by RinkaKanin** [comment]
Hello! I am currently using this method for spatial analysis of seagulls as part of my master's! Trip counts for each gull were successful by using their nest locations (not shared as a population). However, I encountered some issues, where all trips are considered complete and returned, even with adjusted returnBuff and rmNonTrip. I assume this affects the result? Thank you for your work on this package!

**Comment by steffenoppel** [comment]
Hi Rinka, thank you for using this package. Could you please elaborate what 'issues' you have encountered? If all of your gulls have indeed 'returned' to their colony then all trips would be considered complete and returned - why do you think this should be a problem? Whether this affects your 'Result' depends on your question and how you process (or filter) the movements that do not qualify as a trip. We may need a reproducible example to understand your problem.

**Comment by RinkaKanin** [comment]
I appreciate the fast response! I attached a portion of the dataframe of two gulls and the script, as it is easier to reproduce the issue. J13HE seems to get loose ends in mapTrips, while J04HE does not.  To my understanding, these loose ends get excluded by rmNonTrip  = TRUE. Is this to be expected by tracking J13HE for just 2 days, in contrast to J04HE at 49 days? I apologise if it's not relevant!

[Example_gulls.txt](https://github.com/user-attachments/files/19161471/Example_gulls.txt)
[J04HEtrip.csv](https://github.com/user-attachments/files/19161338/J04HEtrip.csv)
[J13HEtrip.csv](https://github.com/user-attachments/files/19161339/J13HEtrip.csv)

**Comment by mdalton1** [comment]
Hello, I have some puffin tracking data and am trying to use the tripSplit function to get trip summaries for each bird. However, the metrics given in the trip summaries do not seem to make sense when I plot the GPS locations over time. It seems like it is grouping multiple distinct trips into one. I've also noticed that a trip will end at the wrong time; for example, a trip seems to conclude not when the bird comes back within the return buffer to spend time at the colony, but only when another trip is about to begin (thereby recording all the time spent at the colony as part of the previous trip). 

Here is some code and the source file. I appreciate any help anyone can give me. Hi @steffenoppel! Nice to see you here :)

[ATPU 2024.csv](https://github.com/user-attachments/files/25083734/ATPU.2024.csv)
[BEN03.csv](https://github.com/user-attachments/files/25083735/BEN03.csv)
[Trip summary and graph code BEN03.txt](https://github.com/user-attachments/files/25083754/Trip.summary.and.graph.code.BEN03.txt)
[BEN03 Trip Summary 2024.csv](https://github.com/user-attachments/files/25083758/BEN03.Trip.Summary.2024.csv)

The plotly graph at the very bottom of the code allows you to zoom in to see time stamps etc.

**Comment by steffenoppel** [comment]
Hi Megan - thank you for that question. I looked at your data and the problem is likely that for a burrow-nesting species like the puffin you do not have enough locations on land (=at the colony) so that trips can be anchored properly. In your code you used extremely small radii for innerBuff (0.25) and returnBuff (0.5), but when I look at your data there are actually very few locations within 1 km of the island. That means that any trip that is started will never end, because no locations return into the 'returnBuff' radius. If you simply change innerBuff to 15 and returnBuff to 5 then you get 3 separate trips. You may need to tweak these numbers, but your bird must return to within the 'returnBuff' radius for a trip to be completed, otherwise the algorithm assumes the bird is still on the first trip. Hope that helps!

<img width="972" height="90" alt="Image" src="https://github.com/user-attachments/assets/7e7a0d6e-2dbc-463d-812b-f1a4bd89d9ae" />

**Comment by mdalton1** [comment]
Hi Steffen, thanks very much for the reply and for the mapping code you sent. It makes sense that a burrowing species would be more difficult to register as at the colony. 

I played with the buffer numbers but it still wasn't making sense to me. I was having trouble understanding why I would see a return to the colony in the distance vs. time plot, but not have that reflected in the GPS points on the map (or in the tripSplit summary). But I think I've figured out the issue... our GPS tags would remotely connect to a base station that was located in the colony when the bird was nearby and the tag would register as 'in range.' In my code I've assigned those 'in range' rows to always be a distance of -50 m from the colony (to help pick these out on the plot). So it looks like sometimes the bird's return isn't recorded as a GPS point, but because it is 'in range' I see that the colony return is reflected in my plot. Though a real GPS point doesn't actually exist so it doesn't get picked up by the tripSplit function. I'll see if I can find a workaround.

That mapping code helped me figure it out in the end, thanks!

**Comment by steffenoppel** [comment]
Hi Megan, ah - that explains a lot! If no actual GPS point exists (with timestamp, lat, long) then the tripSplit function can of course not recognize the return to the colony. As a workaround I would suggest that you manually 'insert' some GPS point (colony coordinates +/- 25 m) at the timestamp when the tag was detected 'in range' and then try the tripSplit function again. But I am not surprised that it cannot work if the in-colony GPS locations are missing from your input data.
