### ISSUE TITLE
formatFields

### ISSUE THREAD

**Issue by steffenoppel** [BirdLifeInternational/track2kba#44]
Just tried to run the code using your boobies data, I keep getting the following error message:

> # ?boobies  # for some background info on the example data set 
> 
> dataGroup <- formatFields(
+     dataGroup = boobies, 
+     fieldID   = "track_id", 
+     fieldDate = "date_gmt", 
+     fieldTime = "time_gmt",
+     fieldLon  = "longitude", 
+     fieldLat  = "latitude"
+ )

_**No format supplied for Date and Time fields, a default format ('ymd_HMS')
      attempted when combining the fields. If error produced, see help page
      ('?lubridate::parse_date_time') for information on date formats.**_ 

Does the data need to be reformatted such as the date and time?

_Originally posted by @pennybeaver in https://github.com/BirdLifeInternational/track2kba/issues/43#issuecomment-1278545128_

**Comment by steffenoppel** [comment]
Hi @pennybeaver, 
this is not an error message, but just an information, and when you execute the code you will get a new field that is in a properly formatted POSIXct format (called 'DateTime'). So yes, the 'Date' and 'Time' fields which are supplied as character values in the data set 'boobies' need to be reformatted - and that is exactly what the function 'formatFields' does.

You should see the dataGroup then containing an additional variable called 'DateTime':

![image](https://user-images.githubusercontent.com/18458206/195786474-57ffab3d-df7f-45d0-9f8c-3f65af083717.png)

Or do you not get this output? Please clarify what your issue is?

**Comment by pennybeaver** [comment]
Thank you Steffen, I was concentrating on the incorrect data frame, I confirm that I get the output as per your output above.
