### ISSUE TITLE
findSite fails if KDEs cross dateline

### ISSUE THREAD

**Issue by halpinlr** [BirdLifeInternational/track2kba#45]
findSite function fails if KDE surfaces cross dateline. 

`Site <- findSite(
  KDE = KDE$KDE.Surface,
  represent = repr$out,
  levelUD = 50,
  popSize = 19000,   
  polyOut = TRUE
  )
`

`Sitemap <- mapSite(Site, colony = colony)`
> Error in wk_handle.wk_wkb(wkb, s2_geography_writer(oriented = oriented,  : 
  Loop 0 is not valid: Edge 4 is degenerate (duplicate vertex)

Simple solution is to reproject Site object to e.g. Lambert Azimuthal Equal Area projection

**Comment by MartinBeal** [comment]
Regarding findSite (and then the mapSite), I believe the issue relates specifically to the the polygon output. When requesting polygon output (i.e. via polyOut = TRUE), issues arise when these projected polygons are internally transformed back to WGS84 (i.e. lat/lon). Are you saying that when you simply transform 'Site' object back to LAEA that the issues are resolved?

For my own recent analyses, the solution I came up with for this was to run both estSpaceUse and findSite using polyOut=FALSE, which both runs faster and avoids this issue (i.e. no internal backtransformation happens). However, doing this then requires bespoke code for (1) identifying the desired contour level in the raster (e.g. 50%) and (2) then converting the raster format to polygons for plotting etc. [Here is the source code I use to do these extra steps](https://github.com/MartinBeal/source_scripts/blob/main/UD_fxns.R).

**Comment by halpinlr** [comment]
Hi Martin,
Yes, it's a quick and not necessarily elegant solution, but simply reprojecting the Site object to LAEA does fix the issue of findSite not working.
